import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <header className="bg-gray-100 p-4 shadow-md sticky top-0 z-50">
          <nav className="container mx-auto flex justify-between items-center">
            <div className="text-2xl font-bold text-gray-800">
              Rudra Ayusham
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
